### ISSUE TITLE
MAY I JOIN?

### ISSUE THREAD

**Issue by radioblahaj** [ScratchFun/scratchfun.github.io#1]

**Comment by Sheshank-s** [comment]
Probably not, I think this is something that only me and csf will be working on, sorry. But you can always make PR

**Comment by csf30816** [comment]
Sorry ToroTV but this is being made only by me, @GreenBayRules, @WorldLanguages, and @ateesdalejr

**Comment by Sheshank-s** [comment]
WorldLanguages is doing this too?

**Comment by radioblahaj** [comment]
Why?

On Sep 28, 2017 7:09 PM, "csf30816" <notifications@github.com> wrote:

Sorry ToroTV but this is being made only by me, @GreenBayRules
<https://github.com/greenbayrules>, @WorldLanguages
<https://github.com/worldlanguages>, and @ateesdalejr
<https://github.com/ateesdalejr>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ScratchFun/scratchfun.github.io/issues/1#issuecomment-332988056>,
or mute the thread

**Comment by ateesdalejr** [comment]
@Torotv Too many unproductive contributors, like me, and your project becomes a mess. ;)

**Comment by Sheshank-s** [comment]
@Torotv Well that and you have a HUGE history of copying especially through me, and my experiences with you haven't been very pleasant,

**Comment by radioblahaj** [comment]
I am sorry. I will no longer copy now. I promise. I am so skrry for what i have done. Please forgive me.
